### ISSUE TITLE
Windows build link is not working

### ISSUE THREAD

**Issue by FinalFrontierPrototyping** [tschoonj/xmimsim#104]
The following link is not working anymore: http://lvserver.ugent.be/xmi-msim

Gateway Timeout
Server error - server 157.193.115.121 is unreachable at this moment.
Please retry the request or contact your administrator.

**Comment by tschoonj** [comment]
Yeah, that server has been taken offline some time ago. Download packages from the releases section instead: https://github.com/tschoonj/xmimsim/releases/tag/XMI-MSIM-8.1

**Comment by FinalFrontierPrototyping** [comment]
Thanks! Perhaps a good idea to remove the link.

**Comment by tschoonj** [comment]
I updated the wiki, the link should have been removed now
