### ISSUE TITLE
xmimsim plugin error

### ISSUE THREAD

**Issue by chenggoi** [tschoonj/xmimsim#2]
Hi:
I have got an error like this:
![error](http://7tsyx2.com1.z0.glb.clouddn.com/error.PNG)
I find that there are three functions in the source code [xrmc-xmimsim.c](https://github.com/golosio/xrmc/blob/master/src/xmi-msim/xrmc-xmimsim.c) ,but only two functions in the dll file like the photo below.So I wanna to know how to solve this problem,thank you.
![dll_function](http://7tsyx2.com1.z0.glb.clouddn.com/dll_function.PNG)

**Comment by tschoonj** [comment]
Thanks for bringing this to my attention. I fixed this in master. A new release is probably still a couple months away though. Can you compile this yourself on Windows?

**Comment by chenggoi** [comment]
OK，really thank you~
