### ISSUE TITLE
Libcurl issue

### ISSUE THREAD

**Issue by NGeorgescu** [tschoonj/xmimsim#44]
Debian Buster and others moves from libcurl 3 to libcurl 4.  Applications like virtual box have upgraded. This application seems to still need older versions of dependencies.

**Comment by tschoonj** [comment]
I haven't made packages for Buster yet... will try and do that today. Do not try and install the packages that I put out for Stretch, they will indeed cause dependency trouble.

**Comment by NGeorgescu** [comment]
No worries. One could make a docker image. 

Libcurl in particular has been such a headache in terms of getting everything on the same version which conflicts with curl and libcurl4.

**Comment by tschoonj** [comment]
Done.

Assuming you already imported the key, add the following line to `/etc/apt/sources.list`:

```
deb http://lvserver.ugent.be/apt/debian buster stable
```

**Comment by NGeorgescu** [comment]
Wow Quick Turnaround! It works! Thanks!
