### ISSUE TITLE
Zero pulse width is invalid

### ISSUE THREAD

**Issue by woutdenolf** [tschoonj/xmimsim#47]
I have noticed that the GUI does not allow me to save the _xmsi_ file when the pulse width is zero. Also the _xmso_ output of _xmimsim-pymca_ contains a zero pulse width, which prevents me from converting it to an _xmsi_ file with _xmso2xmsi_. Is there a reason why pulse width zero is considered invalid?

**Comment by tschoonj** [comment]
The pulse width is used whenever the user invokes `xmimsim` with the `--enable-pile-up` option. For this to work the pulse width must be greater than zero.

I will write a patch to ensure that `xmimsim-pymca` creates xmso files containing a non-zero pulse width.
