### ISSUE TITLE
Tube spectrum

### ISSUE THREAD

**Issue by analecastro** [tschoonj/xmimsim#58]
Hello.
I have been using XMI-MSIM to simulate X-ray fluorescence spectra and perform a comparison with the experimental results obtained. For a better comparison between the results it is important that the X-ray tube data are similar, for this I am trying to replace the X-ray tube spectrum that already exists in XMI-MSIM with the X-ray tube spectrum used in the experimental analyzes . Could you give me an instruction on how I can make this replacement?
Thank you for your attention.

**Comment by tschoonj** [comment]
Hi!

Importing existing excitation spectra is certainly supported. You can use the **Import** button in the discrete lines and continuous intervals widgets to do this. More information about the expected format of the file can be found [here](https://github.com/tschoonj/xmimsim/wiki/User-guide#excitation):

> Import: import a list of discrete lines or continuous energy intensity densities from an ASCII file. These files must consist of either two, three or seven columns, with the first column containing the energies, the second the total intensity (if only two columns are found), or the second and third the resp. horizontally and vertically polarized intensities or intensity densities. If seven columns are encountered, the last four columns are assumed to contain source sizes and divergencies. It is possible through the interface to start reading only at a certain linenumber and also to read only a set number of lines.
