### ISSUE TITLE
xmi_detector_convolute_spectrum coding query

### ISSUE THREAD

**Issue by jenb892** [tschoonj/xmimsim#67]
In file xmi_detector_f.F90, function xmi_detector_convolute_spectrum, line 506 is:

`B0=C*FWHM`

What is C on this line?

**Comment by tschoonj** [comment]
`c` is defined here:

https://github.com/tschoonj/xmimsim/blob/405fd42cd10dde160752e5eb126484c32a273e0a/src/xmi_detector_f.F90#L358-L359


It's a conversion factor between FWHM and standard deviation

**Comment by jenb892** [comment]
Ok, thanks for your prompt reply.
