### ISSUE TITLE
Custom detector response function

### ISSUE THREAD

**Issue by bbazi** [tschoonj/xmimsim#84]
Hi Tom,
Have installed XMI-MSIM-8.1-win64.exe and can successfully simulate the provided examples.
My goal is to implement a custom detector response function for a new HPGe detector.
I am following the Fortran instructions as written down in the Wiki section on how to build modules on Windows.

As a test I'm using the detector-response1.F90 file (taken from XMI-MSIM_64-bit\Sources\xmimsim-8.1\custom-detector-response) but added again the choice for detector types with the magic number stuff. See attached the exact file I'm using.
[detector-response1.zip](https://github.com/tschoonj/xmimsim/files/7519771/detector-response1.zip)

It is then asked to compile the source files and link the objects together, this I could do for the detector response file with no issue (see image).
![Fortran instructions](https://user-images.githubusercontent.com/82967994/141286275-053fcad9-b573-4610-a486-1632a52ba838.png)

Unfortnately, after this I cannot open the XMIMSIM gui, "libxmimsim-gui-0.dll cannot be found" is given as error message.
I'm guessing I have to compile other source files as well..., if so, which ones?
Any news is appreciated!

Cheers,
Benjamin

**Comment by tschoonj** [comment]
Hi Benjamin,

You mean that you cannot open the GUI via the Windows Start menu? Or via the MSYS2 shell? In the latter case it probably means that your PATH variable is not pointing to the Bin folder within the XMI-MSIM folder that contains (some of) the dlls that it needs.

**Comment by tschoonj** [comment]
I would also recommend that you do the development of the plugin on Linux, and only when you get it working there, you move to Windows if you need to create a build of the plugin that is specific to that platform.

**Comment by bbazi** [comment]
Hi Tom,
Yes, I was no longer able to open the GUI via the Windows Start menu or the MSYS2 shell.
Have now moved to Debian "Bullseye" Linux as you recommended, am following the Wiki installation instructions.
The Wiki mentions that only Debian "Strech" is supported, will the newer version give issues? I could not find Stretch on debian.org... 
The update of the apt cache went smooth (see image).
 
![Update Debian apt cache](https://user-images.githubusercontent.com/82967994/141478266-cc97d86d-67e0-43e5-94fc-6c0550288aec.png)

When installing XMI-MSIM, some packages could not be installed (see image), any idea how to fix this?

![Installing xmimsim packages](https://user-images.githubusercontent.com/82967994/141478597-4f1821cd-8ac7-488e-b2df-3a51df7e26c1.png)

Cheers,
Benjamin

**Comment by tschoonj** [comment]
Bullseye is also supported, even though the wiki doesn't mention it explicitly (still need to update that).

Just replace `buster` with `bullseye` in your apt config file, run `sudo apt-get update`, and try installing XMI-MSIM again.

Not sure why you can't open XMI-MSIM in Windows after compiling your plugin. Doesn't make any sense to me. Did you modify the system PATH variable?

**Comment by bbazi** [comment]
Hey,
Nope, didn't change the PATH...
In the meantime, XMI-MSIM has been successfully installed on Bullseye and could perfectly simulate the examples.
How do I now implement a custom detector response function? The Wiki mentions that the development packages have to be included, are these automatically installed? If so, where can I find them?
Cheers,
Benjamin

**Comment by tschoonj** [comment]
Try:

```
sudo apt-get install libxmimsim0-dev
```

**Comment by bbazi** [comment]
Hey,
After installing libxmimsim0-dev I still cannot find the xmi_detector_f.F90 file or any .F90 file in general.
Any idea how to  grab those?
What I have at the moment:
- C/C++ Headers and MOD-files under /usr/include/xmimsim
- C/C++ Headers under /usr/include/xmimsim-gui
- XMSI and XMSO example files under /usr/share/xmimsim

Cheers, B

**Comment by tschoonj** [comment]
You don't need those files for compilation or linking, but you will need to point the fortran compiler to the location of those MOD files. Of course it will be useful for you to look at those files to know the subroutine and function signatures, so best to keep those files open in Github or so.

**Comment by bbazi** [comment]
There seems to be an issue with the PKG_CONFIG_PATH, although libxmimsim.pc is located in the path that will be checked, pkg-config doesn't find it (see image). Any idea what is going wrong?

![pkg-config error](https://user-images.githubusercontent.com/82967994/141652435-761784c0-df42-40a8-8dc1-30d799080513.png)

Cheers, B

**Comment by tschoonj** [comment]
Use backticks instead of regular quotes

**Comment by bbazi** [comment]
Okay, now I get the following dllexport message, should I be worried about this? (see image).

![dll export error](https://user-images.githubusercontent.com/82967994/141653034-bb0bc95f-af54-43e5-9448-36683e246b81.png)

This was the test detector response function I used:
[detector-response1.zip](https://github.com/tschoonj/xmimsim/files/7532449/detector-response1.zip)

Cheers, B

**Comment by tschoonj** [comment]
Nope that's ok. By the way there's no reason to be root for any of this 😁

**Comment by bbazi** [comment]
Okay, I was hesitating :p
I could successfully link the objects together, am now running a simulation with this custom detector response function.
The goal is to play around with the magic number stuff, I'm guessing I can keep recompiling/linking a custom detector response function in an iterative manner? If not, please correct me.

Cheers, B

**Comment by tschoonj** [comment]
That's indeed how I expect that it will go. 

By the way it should be possible to write a detector response plugin that calls Python code, but that would require quite a bit of work...

**Comment by bbazi** [comment]
I will keep it in mind should I need it.
Thanks very much for the help!
Cheers, B
